// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "MVVMTK0045:Using [ObservableProperty] on fields is not AOT compatible for WinRT", Justification = "<pendiente>", Scope = "member", Target = "~F:RolViewModel._rolSeleccionado")]
[assembly: SuppressMessage("Usage", "VSTHRD100:Avoid async void methods", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Pages.RolPage.GuardarOverlay_Click(System.Object,Microsoft.UI.Xaml.RoutedEventArgs)")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowClienteAsync(PrimePOS.WinUI.Overlays.ClienteOverlay,PrimePOS.WinUI.ViewModels.ClienteOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowClienteAsync(PrimePOS.WinUI.Views.Overlays.ClienteOverlay,PrimePOS.WinUI.ViewModels.ClienteOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowCajaAsync(PrimePOS.WinUI.Views.Overlays.CajaOverlay,PrimePOS.WinUI.ViewModels.Overlays.CajaOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowCategoriaAsync(PrimePOS.WinUI.Views.Overlays.CategoriaOverlay,PrimePOS.WinUI.ViewModels.Overlays.CategoriaOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowRolAsync(PrimePOS.WinUI.Views.Overlays.RolOverlay,PrimePOS.WinUI.ViewModels.Overlays.RolOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowProductoAsync(PrimePOS.WinUI.Views.Overlays.ProductoOverlay,PrimePOS.WinUI.ViewModels.Overlays.ProductoOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowUsuarioAsync(PrimePOS.WinUI.Views.Overlays.UsuarioOverlay,PrimePOS.WinUI.ViewModels.Overlays.UsuarioOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowTurnoAsync(PrimePOS.WinUI.Views.Overlays.AbrirTurnoOverlay,AbrirTurnoViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowCerrarTurnoAsync(PrimePOS.WinUI.Views.Overlays.CerrarTurnoOverlay,CerrarTurnoViewModel)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowCerrarTurnoAsync(PrimePOS.WinUI.Views.Overlays.CerrarTurnoOverlay,CerrarTurnoViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowCobrarAsync(PrimePOS.WinUI.Views.Overlays.CobrarOverlay,PrimePOS.WinUI.ViewModels.CobrarViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowAsync(Microsoft.UI.Xaml.Controls.UserControl,PrimePOS.WinUI.Contracts.IOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowLoginAsync(LoginViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.AuthOverlayService.ShowLoginAsync(LoginViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "VSTHRD003:Avoid awaiting foreign Tasks", Justification = "<pendiente>", Scope = "member", Target = "~M:PrimePOS.WinUI.Services.OverlayService.ShowLoginAsync(LoginOverlayViewModel)~System.Threading.Tasks.Task{System.Boolean}")]
